# -*- coding: utf-8 -*-
"""emoji-clean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHLwVaD_suZiE2jTRUkGxq6l79zQXVG_
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

!pip install emoji

import numpy as np
import pandas as pd
import csv
import emoji

df = pd.DataFrame(pd.read_csv('olid-training-v1.0.tsv', sep='\t'))
df.to_csv('trainingset.csv',index=False)
csv_file = open('trainingset.csv')
csv_reader_lines = csv.reader(csv_file)
data=[]

counter = 0
for lines in csv_reader_lines:
    line_container = []
    line_container.append(lines[0])
    # print(lines[1])

    # Remove all "@USER" and "URL" and "#""
    container = lines[1].replace("@USER","")
    container = container.replace("URL","")
    container = container.replace("@","")

    container = emoji.demojize(container)

    # Remove symbols
    container = container.lower()
    container = container.replace("#","")
    container = container.replace("%","")
    container = container.replace("?","")
    container = container.replace("!","")
    container = container.replace(","," ")
    container = container.replace(".","")
    container = container.replace("“","")
    container = container.replace("”","")
    container = container.replace("&","")
    container = container.replace("(","")
    container = container.replace(")","")
    container = container.replace("/"," ")
    container = container.replace(";","")
    container = container.replace("-"," ")
    container = container.replace("—"," ")
    container = container.replace(":","")
    container = container.replace("~","")
    container = container.replace("_"," ")
    container = container.replace("\"","")
    container = container.replace("'","")

    # Convert Be
    container = container.replace("'m"," am")
    container = container.replace("’m"," am")
    container = container.replace("’re"," are")
    container = container.replace("'re"," are")

    # Convert Have
    container = container.replace("'ve"," have")
    container = container.replace("’ve"," have")

    # Convert 's
    container = container.replace("it’s","it is")
    container = container.replace("it's","it is")
    container = container.replace("what’s","what is")
    container = container.replace("There’s","there is")
    container = container.replace("he’s","he is")
    container = container.replace("she’s","she is")
    container = container.replace("that's","that is")
    container = container.replace("let's","let us")
    container = container.replace("’s","")
    container = container.replace("'s","")

    # Convert Not
    container = container.replace("n’t"," not")
    container = container.replace("n't"," not")
    
    # Convert 'll 
    container = container.replace("'ll"," will")

    # Show *
    container = container.replace("sh*t","shit")
    container = container.replace("f**k","fuck")

    

    container = container.lower()
    container = container[:0]+'\''+container[:]+'\''

    # Store results after filtering
    line_container.append(container)
    line_container.append(lines[2])
    # line_container.append(lines[3])
    # line_container.append(lines[4])
    # print("-------", container)
    # print(line_container)
    data.append(line_container)

#     counter +=1
#     if counter == 200:
#         break

# for line in data:
#     print(line)

path = "output.csv"
with open(path, 'w+') as f:
      csv_write = csv.writer(f)
      # csv_head = data[0]
      # csv_write.writerow(csv_head)
      for line in data:
          csv_write.writerow(line)

! ls

files.download('output.csv')
